environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
os: Visual Studio 2017 # Windows Server 2016
install:
  - java -version
build_script:
  - gradlew.bat -u -i -S --no-daemon build
test_script:
  - gradlew.bat -u -i -S --no-daemon check
cache:
  - C:\Users\appveyor\.gradle
